### ISSUE TITLE
感谢作者提供的as算法

### ISSUE THREAD

**Issue by YzzlManual** [zhangpanyi/a-star-algorithm#2]
感谢作者在我临急的时候提供了这个开源源码.

另:个人感觉可以把初始化地图生成数据去掉, 等寻到可用点的时候再动态生成, 寻路多数是不用遍历所有点的.可以减少内存申请和删除的开销.

**Comment by zhangpanyi** [comment]
其实那里也占用不了多少内存，只是用来存放指针的。不过我正考虑把那部分换成十字链表。

**Comment by YzzlManual** [comment]
意思也不是在占用内存, 我认为as内部不需要关心地图有多大, 也不需要自身生成地图数据, 因为有can_reach function的存在, 因此我们把这个任务交给这个函数就可以了. 寻找可用的点的时候, 创建(目前也是这么做), 
寻路完成释放空间不需要每个指针遍历, 只需要删除创建项目就可以(我改了这个, 也如同你所说, 我也换成了十字链表),
目前这个改动已经应在自己项目上. 速度上会比原来稍好些.
ps: 有些地方我不太清楚作者是否别有用意, 在删减修改后的现在代码行数大约只有原来的2/3不到.

**Comment by zhangpanyi** [comment]
你可以帮我测试一下特大地图的情况下用十字链表会不会频繁地分配内存从而导致速度下降

---

发件人: YzzlManual notifications@github.com
发送时间: 2016年10月11日 6:33
收件人: zhangpanyi/a-star-algorithm
抄送: playz; Comment
主题: Re: [zhangpanyi/a-star-algorithm] 感谢作者提供的as算法 (#2)

意思也不是在占用内存, 我认为as内部不需要关心地图有多大, 也不需要自身生成地图数据, 因为有can_reach function的存在, 因此我们把这个任务交给这个函数就可以了. 寻找可用的点的时候, 创建(目前也是这么做),
寻路完成释放空间不需要每个指针遍历, 只需要删除创建项目就可以(我改了这个, 也如同你所说, 我也换成了十字链表),
目前这个改动已经应在自己项目上. 速度上会比原来稍好些.
ps: 有些地方我不太清楚作者是否别有用意, 在删减修改后的现在代码行数大约只有原来的2/3不到.

―

**Comment by ytgui** [comment]
这代码真心写的不错，赞+感谢
