### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by kamfon** [zhangpanyi/a-star-algorithm#4]
你好， 经仔细阅读代码之后，发现  AStar :: clear() 函数里存在可能导致内存泄漏的bug：

该函数的while循环里的第二句代码（即 index++）应该去掉，否则会造成index变量在一次循环里自增了两次，正确的话应该是只自增一次。

麻烦你确认一下。

**Comment by zhangpanyi** [comment]
感谢指正
