### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by kamfon** [zhangpanyi/a-star-algorithm#5]
你好， AStar :: calcul_h_value()函数的实现有误。
abs(end.y + end.x - current.y - current.x) 应该改为：

abs(end.x - current.x) + abs(end.y - current.y)

上面两种写法，是不等价的。  比如：考虑当end为(1, 2), current为(2, 1)时，上面两种写法结果不一样。
同理， astar.cpp里其他用到abs()函数的地方，也都有类似的问题，比如计算G值的函数。

麻烦你确认下。

**Comment by zhangpanyi** [comment]
感谢指正，的确存在这个问题
